### ISSUE TITLE
I am getting this error from Server.py please update this script

### ISSUE THREAD

**Issue by Kamalbilal1675** [nastyzera/Torrent-Drive-Telegram-Bot-Using-Colab#2]
Traceback (most recent call last):
  File "server.py", line 68, in <module>
    reply = make_reply(message)
  File "server.py", line 54, in make_reply
    return reply
UnboundLocalError: local variable 'reply' referenced before assignment

**Comment by DiyRex** [comment]
Traceback (most recent call last):
  File "server.py", line 59, in <module>
    updates = updates["result"]
KeyError: 'result'

I got this error
